sudo: false
language: node_js
node_js:
  - stable
  - 4
install:
  - npm prune
  - npm update
after_success:
  - npm run coveralls
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: dominic@dbarnes.info
  api_key:
    secure: FNTGoM5iiOynJw0EL2+J3ejLpoSWOsPODj68tQPRCYgLZwjj8I6/4qiiM0sFpKBrTlnTCuyQIs6zz2kLsvLtH/jEWiD6l57i3C9aoAGroOOh2YyywPdl5Q4sharMvWxjnmP2L+6gi9gw2FANzGpDWWS4KUPaA2HA3dTsIDVuZm2yZrYFXppyA9uNuMM4lFmJRdDq1M1EtXsbIczWnC09t1sN11nJ4wH5J1GavwqhfeYK/gZiezn/rfujDzF+zXRQZsCs4/pPK9yyF6X05aqPuBmVhVFMjtTYNHviKXaAKugSrg8Q/Xk/g88M41Z6ZzdIW4EQ9hNKcC0112rv5fJ7sLwY7C/tD+cwFzDkG2qYJXl968JEwESJ1jrRlrL1RjmCZz9iyGPOJ9Xtnuk762U01pabKfnZnkgO0jURd9A0DaRn4aHWO6m1GoI3LM0lo/ygF/n05Flxw2u0ux8BHGFoprffmOjwzxOTBQ4yrqgDR1KFl+OFjLJ5Zc21zbwsvCXzOVpl4E0kgIogEb4erALYX3Ogc3eA6Ih/sPjgpZeQ91si9QVvvTrAKMWVJxh/Gfyy/LcUQM19nn4N3PjnCdKlAtrDxBDBTPZ5VLKbp2k86HVCnF1FFteAIoeCvTbfW+Xwd7Kbpc3DlJud2l1RVF7ow9KzPGyXWIkvVtPtgxkzUsU=
  on:
    tags: true
    repo: makojs/browser
    node: stable
